In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('iw_uk.csv', index_col=0)

/var/folders/82/y6qdnkm17_j10_7ddv31f_mw0000gn/T/ipykernel_35550/2441918933.py:1: DtypeWarning: Columns (0: source, 1: registrant_additional_information, 2: portal_source) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('iw_uk.csv', index_col=0)

In [11]:
df.head()

,rep_new,policy_level,date,organisation,purpose,department,Quarter,others_at_the_meeting,source,registrant_additional_information,portal_source,RecordId,tag
0,Rt Hon Dominic Grieve QC,1,01/01/2012,Criminal Law Commission,To discuss contempt issues,Attorney General's Office,Q1,NaN,NaN,NaN,UK Government,1,NaN
1,Rt Hon Dominic Grieve QC,1,01/02/2012,Federalist Society,To discuss the EU Court of Human Rights,Attorney General's Office,Q1,NaN,NaN,NaN,UK Government,2,NaN
2,Rt Hon Dominic Grieve QC,1,01/02/2012,Magistrates Association,To discuss the magistrates sentencing powers,Attorney General's Office,Q1,NaN,NaN,NaN,UK Government,3,NaN
3,Rt Hon Dominic Grieve QC,1,01/02/2012,Bar Council,Regular catch up meeting,Attorney General's Office,Q1,NaN,NaN,NaN,UK Government,4,NaN
4,Rt Hon Dominic Grieve QC,1,01/03/2012,Sir Daniel Bethlehem QC & Sir Jeffery Jowell QC,To discuss Bahrain issues,Attorney General's Office,Q1,NaN,NaN,NaN,UK Government,5,NaN

In [12]:
df.shape, df.RecordId.max()

((166368, 13), np.int64(22744976))

In [13]:
df.tail()

,rep_new,policy_level,date,organisation,purpose,department,Quarter,others_at_the_meeting,source,registrant_additional_information,portal_source,RecordId,tag
166363,Rt Hon Maria Eagle MP,1,15/07/2025,Vertical Aerospace,Introduction meeting,Ministry of Defence,Q3,NaN,UK Government,NaN,UK Government,1110792,Defence
166364,Al Carns MP,1,18/09/2025,"The Royal British Legion, SRRA, SASRA, SBSA, M...",To discuss the Northern Ireland Legacy,Ministry of Defence,Q3,NaN,UK Government,NaN,UK Government,1110793,Defence
166365,Louise Sandher-Jones MP,1,07/07/2025,Fighting With Pride,Priorities and Remberance Discussions,Ministry of Defence,Q3,NaN,UK Government,NaN,UK Government,1110794,Defence
166366,Louise Sandher-Jones MP,1,01/09/2025,NASUWT - The Teachers' Union,Discussion about Ministry of Defence School Te...,Ministry of Defence,Q3,NaN,UK Government,NaN,UK Government,1110795,Defence
166367,Louise Sandher-Jones MP,1,01/09/2025,Labrats International,Engagement regarding Nuclear Test Veterans,Ministry of Defence,Q3,NaN,UK Government,NaN,UK Government,1110796,Defence

In [22]:
df.loc[df.RecordId.isin([43510, 43511]), ]

,rep_new,policy_level,date,organisation,purpose,department,Quarter,others_at_the_meeting,source,registrant_additional_information,portal_source,RecordId,tag
43491,Jackie Doyle-Price MP,1,15/11/2017,Marie Stopes International,A progress meeting following CQC inspection,Department of Health and Social Care,Q4,NaN,NaN,NaN,UK Government,43510,Health
43492,Jackie Doyle-Price MP,1,15/11/2017,Transforming Care Assurance Roundtable\nSeeAbi...,To hear stakeholders? views and perceptions of...,Department of Health and Social Care,Q4,NaN,NaN,NaN,UK Government,43511,NaN

In [6]:
df.to_json("iw_uk.json", orient="records")